apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-argo-api
  namespace: helm-argo
  labels:
    app: helm-argo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helm-argo
  template:
    metadata:
      labels:
        app: helm-argo
    spec:
      containers:
      - name: helm-argo-api
        image: naderhs/page-nhs-kube:latest
        ports:
        - containerPort: 3000
